---
title: "Compare demographics among missing and non-missing groups"
author: "Kate Tran"
date: "4/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(readxl)
library(gtsummary)
```

```{r}
source("../config.R")
```

```{r}
covid_long <- "../outputs/mixedmodels_dat_final.xlsx" %>% read_excel() %>% 
  mutate(across(c(
                sex_br,
                race_white,
                race_black,
                race_asian,
                race_mixed,
                race_aian,
                race_nhpi,
                race_other,
                ethnicity_hisp,
                non_hispanic_black,
                non_hispanic_white,
                born_in_usa,
                separated_or_divorced,
                parents_married),
                ~ factor(.x, levels = c("0", "1"))))

# Create mean interview_age
covid_long <- covid_long %>% 
  group_by(src_subject_id) %>% 
  mutate(interview_age_mean = mean(interview_age, na.rm = TRUE))

covid_long <- covid_long %>% 
  select(-contains(c("fam_actions", "parent_monitor_q", "pstr", "strle", "su_", "bifactor", "fam_exp")), 
                   -felt_alone_cv, -felt_always_sad, -felt_cv, -felt_life_went_wrong_cv, -felt_lonely_cv, 
                   -felt_no_fun_cv, -felt_sad_cv, -felt_unhappy_cv, -outdoor_act_cv)
```

# 1. COMPARE MISSING AND NON-MISSING OF OUTCOME felt_sad_cv_raw_tot_bar

```{r}
outcome_nonNAs <- covid_long %>% 
  filter(!is.na(felt_sad_cv_raw_tot_bar)) %>% distinct(src_subject_id, .keep_all = TRUE) %>%  # 7867
  mutate(outcome_missing = 0)

# outcome_NAs are those who are not in outcome_nonNAs
outcome_NAs <- covid_long %>% 
  filter(!src_subject_id %in% unique(outcome_nonNAs$src_subject_id)) %>% distinct(src_subject_id, .keep_all = TRUE) %>%  # 1853
  mutate(outcome_missing = 1)

covid_wide_comp <- outcome_nonNAs %>%
  bind_rows(outcome_NAs) %>% 
  dplyr::select(-timepoint, -eventname)
```

```{r}
compared_var <- c("interview_age_mean",
                  "sex_br",
                  "race_white",
                  "race_black",
                  "race_asian",
                  "race_mixed",
                  "race_aian",
                  "race_nhpi",
                  "race_other",
                  "ethnicity_hisp",
                  "non_hispanic_black",
                  "non_hispanic_white",
                  "born_in_usa",
                  "household_income",
                  "parents_avg_edu",
                  "separated_or_divorced",
                  "parents_married")

     
outcome_NAs_summ <- covid_wide_comp %>% 
  dplyr::select(outcome_missing, all_of(compared_var)) %>% 
  tbl_summary(
    by = outcome_missing,
    statistic = list(all_continuous() ~ "{mean} ({sd})",
                     all_categorical() ~ "{n} ({p}%)"),
    digits = all_continuous() ~ 2,
    missing_text = "Missing",
    include = all_of(compared_var)
  ) %>% 
  modify_header(all_stat_cols() ~ "**{level}**<br>N =  {n} ({style_percent(p)}%)") %>%
  bold_labels() %>%
  modify_spanning_header(all_stat_cols() ~ "**Missing outcome (sadness scale)**") %>% 
  add_p()

outcome_NAs_summ
```