---
title: "Mediation analysis"
author: "Kate Tran"
date: "3/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(readxl)
library(lavaan)
library(lavaanPlot)
library(tidyr)
library(DiagrammeRsvg)
library(rsvg)
library(readr)
library(sjPlot)
library(modelr)
```

```{r}
source("../config.R")
```

```{r}
# Read data from mixed model final long data
covidp_long <- read.csv("../outputs/covidp_long.csv")
covidy_long <- read.csv("../outputs/covidy_long.csv")
family_ <- read.csv("../outputs/family.csv") %>%
  dplyr::select(-eventname)
demo_baseline <- read.csv("../outputs/demographics_baseline.csv")
demographics_long <- read.csv("../outputs/demographics_long.csv")
# exposome_sum_set <- read.csv("../outputs/exposome_sum_set.csv")
p_factor_with_sui <- read_csv(paste0(p_factor_files_path, "ABCD_psychopathology_bifactor_scores_23March2021_WITH_SUICIDALITY.csv"))

p_factor_with_sui$src_subject_id <- paste0("NDAR_", p_factor_with_sui$ID)
p_factor_with_sui$ID <- NULL
colnames(p_factor_with_sui)[1:7] <- paste0(colnames(p_factor_with_sui)[1:7], "_with_sui")


# IVs <- merge(demographics_long, exposome_sum_set, all = T)
IVs <- IVs[(IVs$eventname == "1_year_follow_up_y_arm_1"),]

colnames(IVs)[2] <- "interview_date_before_covid"
colnames(IVs)[3] <- "interview_age_before_covid"
IVs$eventname <- NULL


covid_long_mixed_model <- merge(covidp_long, covidy_long, all = T)
covid_long_mixed_model <- merge(covid_long_mixed_model, family_, all.x = T)
covid_long_mixed_model <- merge(covid_long_mixed_model, IVs)

covid_long_mixed_model <- covid_long_mixed_model %>%
  dplyr::mutate(timepoint = sub("cv", "" , timepoint)) %>%
  dplyr::select(-eventname,-contains("fam_actions_cv"))

# long to wide format
covid_wide <- covid_long_mixed_model %>%
  pivot_wider(
    .,
    names_from = timepoint,
    values_from = c(
      fam_exp_racism_cv:pstr_cv_raw_tot_bar.1,
      ends_with("_l"),
      stq_y_ss_weekday:dim_y_ss_mean
    ),
    names_sep = "_"
  )

demo_baseline <- demo_baseline %>%
  dplyr::select(
    -sex,
    -household_income,
    -parents_avg_edu,
    -separated_or_divorced,
    -parents_married,
    -age,
    -sex_br,
    -gender,
    -demo_fam_poverty,
    -interview_date,
    -interview_age,
    -eventname
  )

covid_wide <- merge(covid_wide, demo_baseline, all.x = T)
covid_wide$rel_family_id <- covid_wide$rel_family_id + 1
covid_wide <- merge(covid_wide, p_factor_with_sui, all.x = T)
```

# Create the wide format

```{r}
covid_wide <- covid_wide %>%
  dplyr::select(
    src_subject_id,
    contains(
      c(
        "fam_wage_loss_cv",
        "work_ability_cv",
        "parent_monitor_tot_bar",
        "felt_sad_cv_raw_tot_bar",
        "money_cv",
        "dim_y_ss",
        "mean",
        "interview_age",
        "worry_y"
      )
    ),
    increased_conflict_cv_1,
    increased_conflict_cv_3,
    increased_conflict_cv_5,
    sex_br,
    race_white,
    race_black,
    race_asian,
    ethnicity_hisp,
    household_income,
    parents_avg_edu,
    # p_factor
    General_p_with_sui
  )


covid_wide <- covid_wide %>%
  rowwise() %>%
  # Create new variables for mediation model
  dplyr::mutate(
    # Summary of IV at t1 and t2, if any = 1 then 1, both 0 then 0, 1NA then NA
    fam_wage_loss_cv_mean12 = case_when(
      fam_wage_loss_cv_1 == 1 | fam_wage_loss_cv_2 == 1 ~ 1,
      fam_wage_loss_cv_1 == 0 & fam_wage_loss_cv_2 == 0 ~ 0,
      TRUE ~ NA_real_
    )
  ) %>%
  dplyr::mutate(
    # Summary of moderators t3&t5 or t3-t6 mean
    ## increased_conflict_cv
    increased_conflict_cv_mean35 = mean(c(
      increased_conflict_cv_3, increased_conflict_cv_5
    ), na.rm = TRUE),
    
    ## work_ability_cv
    work_ability_cv_mean3to6 = mean(
      c(
        work_ability_cv_3,
        work_ability_cv_4,
        work_ability_cv_5,
        work_ability_cv_6
      ),
      na.rm = TRUE
    ),
    
    ## parent_monitor_tot_bar
    parent_monitor_tot_bar_cv_mean3to6 = mean(
      c(
        parent_monitor_tot_bar_3,
        parent_monitor_tot_bar_4,
        parent_monitor_tot_bar_5,
        parent_monitor_tot_bar_6
      ),
      na.rm = TRUE
    ),
    
    ## worries about money T3, T4, T5
    money_cv_mean3to6 = mean(c(money_cv_3, money_cv_4, money_cv_5, money_cv_6), na.rm = TRUE),
  
    ## Discrimination mean 7 time points
    dim_y_ss_mean = mean(
      c(
        dim_y_ss_mean_1,
        dim_y_ss_mean_2,
        dim_y_ss_mean_3,
        dim_y_ss_mean_4,
        dim_y_ss_mean_5,
        dim_y_ss_mean_6,
        dim_y_ss_mean_7
      ),
      na.rm = TRUE
    ),
    
    ## Age at interview mean
    age_mean_cv = mean(
      c(
        interview_age_1,
        interview_age_2,
        interview_age_3,
        interview_age_4,
        interview_age_5,
        interview_age_6,
        interview_age_7
      ),
      na.rm = TRUE
    ),
    
    # Other worries rather than financial worries
    worry_y_cv_mean3to6 = mean(c(worry_y_cv_3, worry_y_cv_4, worry_y_cv_5, worry_y_cv_6), na.rm = TRUE)
  ) 

# Convert to factors
covid_wide <- covid_wide %>%
  dplyr::mutate(across(
    c(
      fam_wage_loss_cv_mean12,
      sex_br,
      race_white,
      race_black,
      race_asian,
      ethnicity_hisp
    ),
    ~ factor(.x, levels = c("0", "1"))
  ))

# writexl::write_xlsx(covid_wide, "../outputs/mediation_dat_final.xlsx")
```

# Add residuals

```{r}
# Residuals of worries
covid_wide <- add_residuals(covid_wide, lm(money_cv_mean3to6 ~ worry_y_cv_mean3to6, data = covid_wide), var = "Residualized_money_cv")


# Residuals of IV
Residualized_IV_cv <- residuals(glm(
      fam_wage_loss_cv_mean12 ~ age_mean_cv + sex_br + race_black + race_white + ethnicity_hisp + household_income,
      data = covid_wide,
      family = binomial
    ))

dat_Residualized_IV_cv <- data.frame(Residualized_IV_cv = Residualized_IV_cv)
dat_Residualized_IV_cv$id <- names(Residualized_IV_cv)

covid_wide$id <- rownames(covid_wide)

covid_wide <- covid_wide %>% 
  left_join(dat_Residualized_IV_cv)
```

```{r}
# covid_wide <- covid_wide %>% 
#   dplyr::select(-contains(c("stq_y", "pmq_y", "src_subject_id")))
# 
# covid_wide <- covid_wide %>% 
#   dplyr::select_if(., function(x)
#     any(!is.na(x)))
# 
# write.csv(covid_wide, "../outputs/mediation_dat_final_Tyler.csv", na = "")
```

# 1. MEDIATOR WORRIES ABOUT MONEY

```{r}
# Regress out M and IV
set.seed(2022)
mod_mean_money_residMIV <- '
Residualized_money_cv ~ a*Residualized_IV_cv
felt_sad_cv_raw_tot_bar_7 ~ c*Residualized_IV_cv + b*Residualized_money_cv
ind := a*b
total := c + a*b
'

med_mod_mean_money_residMIV <- sem(mod_mean_money_residMIV,
                                data = covid_wide,
                                se = "bootstrap",
                                bootstrap = 500)

standardizedSolution(med_mod_mean_money_residMIV, type = "std.all")

labels_mean_money_residMIV = list(
  Residualized_IV_cv = "Wage loss T1-2 \n Regressed out covariates \n (independent variable)",
  felt_sad_cv_raw_tot_bar_7 = "Depressive symptoms T7 \n (outcome)",
  Residualized_money_cv = "Worries about money T3-4-5-6 \n Regressed out other worries \n (mediator)"
)

plot_mean_money_residMIV <- lavaanPlot(
  model = med_mod_mean_money_residMIV,
  labels = labels_mean_money_residMIV,
  node_options = list(
    shape = "box",
    fontname = "Arial",
    color = "blue4"
  ),
  edge_options = list(color = "darkolivegreen"),
  coefs = TRUE,
  stand = TRUE,
  # covs = TRUE,
  digits = 3,
  stars = "regress"
)

# save_png(plot_mean_money_residMIV, "../plots/plot_mean_money_residMIV.png" )
```

For the next analysis, DV will be at time point 7 (cannot do mean 5&7 because no observations of conflict at T4)

# 2. MEDIATOR FAMILIES' PROBLEMS

### M1 + M2 + M3 in the same plot

```{r}
# Regress out IV (no mediator money worries, so no regressed out mediator)
set.seed(2022)
model_1_mean_M1M2M3_regressout_IV <- '
increased_conflict_cv_mean35 ~ fc1*Residualized_IV_cv
parent_monitor_tot_bar_cv_mean3to6 ~ pm1*Residualized_IV_cv
work_ability_cv_mean3to6 ~ pwc1*Residualized_IV_cv
felt_sad_cv_raw_tot_bar_7 ~ mf*Residualized_IV_cv + fc2*increased_conflict_cv_mean35 + pm2*parent_monitor_tot_bar_cv_mean3to6 + pwc2*work_ability_cv_mean3to6
increased_conflict_cv_mean35 ~~ parent_monitor_tot_bar_cv_mean3to6
parent_monitor_tot_bar_cv_mean3to6 ~~ work_ability_cv_mean3to6
work_ability_cv_mean3to6 ~~ increased_conflict_cv_mean35
indM1 := fc1*fc2
indM2 := pm1*pm2
indM3 := pwc1*pwc2
totalindirecteffect := fc1*fc2 + pm1*pm2 + pwc1*pwc2
totaleffect := mf + fc1*fc2 + pm1*pm2 + pwc1*pwc2
'

med_model_1_mean_M1M2M3_regressout_IV <- sem(
  model_1_mean_M1M2M3_regressout_IV,
  data = covid_wide,
  se = "bootstrap",
  bootstrap = 500
)

standardizedSolution(med_model_1_mean_M1M2M3_regressout_IV, type = "std.all")


labels_1_mean_M1M2M3_regressout_IV = list(
  increased_conflict_cv_mean35 = "Family conflict T3-5 \n (mediator 1)",
  Residualized_IV_cv = "Wage loss T1-2 \n Regressed out covariates \n (independent variable)",
  parent_monitor_tot_bar_cv_mean3to6 = "Parental monitoring T3-4-5-6 \n (mediator 2)",
  work_ability_cv_mean3to6 = "Parent-workplace conflict T3-4-5-6 \n (mediator 3)",
  felt_sad_cv_raw_tot_bar_7 = "Depressive symptoms T7 \n (outcome)"
)

plot_mean_M1M2M3_regressout_IV <- lavaanPlot(
  model = med_model_1_mean_M1M2M3_regressout_IV,
  labels = labels_1_mean_M1M2M3_regressout_IV,
  node_options = list(
    shape = "box",
    fontname = "Arial",
    color = "blue4"
  ),
  edge_options = list(color = "darkolivegreen"),
  coefs = TRUE,
  stand = TRUE,
  # covs = TRUE,
  digits = 3,
  stars = "regress"
)

# save_png(plot_mean_M1M2M3_regressout_IV, "../plots/mediator_parentsconflict/plot_mean_M1M2M3_regressout_IV.png")

```


# 3. FAMILIES' PROBLEMS AND FINANCIAL WORRIES

```{r}
set.seed(2022)
model_1_mean_M1M2M3M4_regressout_M_IV <- '
increased_conflict_cv_mean35 ~ fc1*Residualized_IV_cv
parent_monitor_tot_bar_cv_mean3to6 ~ pm1*Residualized_IV_cv
work_ability_cv_mean3to6 ~ pwc1*Residualized_IV_cv
Residualized_money_cv ~ mw1*Residualized_IV_cv
felt_sad_cv_raw_tot_bar_7 ~ mf*Residualized_IV_cv + fc2*increased_conflict_cv_mean35 + pm2*parent_monitor_tot_bar_cv_mean3to6 +
pwc2*work_ability_cv_mean3to6 + mw2*Residualized_money_cv
increased_conflict_cv_mean35 ~~ parent_monitor_tot_bar_cv_mean3to6
parent_monitor_tot_bar_cv_mean3to6 ~~ work_ability_cv_mean3to6
work_ability_cv_mean3to6 ~~ increased_conflict_cv_mean35
Residualized_money_cv ~~ increased_conflict_cv_mean35
Residualized_money_cv ~~ parent_monitor_tot_bar_cv_mean3to6
Residualized_money_cv ~~ work_ability_cv_mean3to6
indM1 := fc1*fc2
indM2 := pm1*pm2
indM3 := pwc1*pwc2
indM4 := mw1*mw2

totalindirecteffect := fc1*fc2 + pm1*pm2 + pwc1*pwc2 + mw1*mw2
totaleffect := mf + fc1*fc2 + pm1*pm2 + pwc1*pwc2 + mw1*mw2
'

med_model_1_mean_M1M2M3M4_regressout_M_IV <- sem(
  model_1_mean_M1M2M3M4_regressout_M_IV,
  data = covid_wide,
  se = "bootstrap",
  bootstrap = 500
)

standardizedSolution(med_model_1_mean_M1M2M3M4_regressout_M_IV, type = "std.all")


labels_1_mean_M1M2M3M4_regressout_M_IV = list(
  increased_conflict_cv_mean35 = "Family conflict T3-5 \n (mediator 1)",
  Residualized_IV_cv = "Wage loss T1-2 \n Regressed out covariates \n (independent variable)",
  parent_monitor_tot_bar_cv_mean3to6 = "Parental monitoring T3-4-5-6 \n (mediator 2)",
  work_ability_cv_mean3to6 = "Parent-workplace conflict T3-4-5-6 \n (mediator 3)",
  Residualized_money_cv = "Worries about money T3-4-5-6 \n Regressed out other worries \n (mediator 4)",
  felt_sad_cv_raw_tot_bar_7 = "Depressive symptoms T7 \n (outcome)"
)

plot_mean_M1M2M3M4_regressout_M_IV <- lavaanPlot(
  model = med_model_1_mean_M1M2M3M4_regressout_M_IV,
  labels = labels_1_mean_M1M2M3M4_regressout_M_IV,
  node_options = list(
    shape = "box",
    fontname = "Arial",
    color = "blue4"
  ),
  edge_options = list(color = "darkolivegreen"),
  coefs = TRUE,
  stand = TRUE,
  # covs = TRUE,
  digits = 3,
  stars = "regress"
)
# summary(med_model_1_mean_M1M2M3M4_regressout_M_IV, standardized=T, fit.measure=T) # get N and the value for 0 in the plot
# save_png(plot_mean_M1M2M3M4_regressout_M_IV, "../plots/mediator_parentsconflict/plot_mean_M1M2M3M4_regressout_M_IV.png")
```

